  const [departments, setDepartments] = useState([
    { 
      id: 1, 
      name: 'Food Pantry Ministry', 
      leaders: ['Deaconness Esinam Segoh'],
      assistant: '',
      secretary: '',
      treasurer: '',
      members: 15, 
      membersList: [],
      budget: 30000,
      expenses: 22000,
      description: 'Providing food assistance to families in need in our community',
      meetingDay: 'Wednesday',
      meetingTime: '6:00 PM',
      meetingLocation: 'Fellowship Hall',
      projects: ['Weekly Food Distribution', 'Holiday Food Baskets', 'Community Outreach'],
      icon: Utensils,
      color: 'green',
      joinRequests: []
    },
    { 
      id: 2, 
      name: 'Faith Klinik Dance Ministers', 
      leaders: ['Enam Egyir'],
      teacher: 'Samuel Ghartey',
      assistant: '',
      secretary: '',
      treasurer: '',
      members: 12, 
      membersList: ['Eyram Kwauvi', 'Edem Kwauvi'],
      budget: 15000,
      expenses: 8000,
      description: 'Expressing worship through dance and movement',
      meetingDay: 'Every Saturday',
      meetingTime: '10:00 AM',
      meetingLocation: 'Main Sanctuary',
      projects: ['Sunday Morning Worship', 'Special Events', 'Youth Dance Training'],
      icon: Music,
      color: 'purple',
      joinRequests: []
    },
    { 
      id: 3, 
      name: 'League of Anointed Ministers (Music Ministry)', 
      leaders: ['Jedidiah Adarquah-Yiadom'],
      assistant: '',
      secretary: '',
      treasurer: '',
      members: 20, 
      membersList: [],
      budget: 35000,
      expenses: 25000,
      description: 'Leading congregation in worship through music and praise',
      meetingDay: 'Every Thursday',
      meetingTime: '7:00 PM',
      meetingLocation: 'Music Room',
      projects: ['Sunday Worship', 'Special Concerts', 'Music Training'],
      icon: Music,
      color: 'blue',
      joinRequests: []
    },
    { 
      id: 4, 
      name: 'Media Ministry', 
      leaders: ['Jasper D.'],
      assistant: '',
      secretary: '',
      treasurer: '',
      members: 8, 
      membersList: [],
      budget: 25000,
      expenses: 18000,
      description: 'Managing audio, video, and digital media for church services',
      meetingDay: 'Second Saturday of the month',
      meetingTime: '2:00 PM',
      meetingLocation: 'Media Room',
      projects: ['Live Streaming', 'Service Recording', 'Website Management'],
      icon: Globe,
      color: 'red',
      joinRequests: []
    },
    { 
      id: 5, 
      name: 'Youth Ministry', 
      leaders: ['Jeshurun Adarquah-Yiadom'],
      assistant: '',
      secretary: '',
      treasurer: '',
      members: 25, 
      membersList: [],
      budget: 30000,
      expenses: 20000,
      description: 'Engaging and discipling the next generation in their faith journey',
      meetingDay: 'Every Friday',
      meetingTime: '7:00 PM',
      meetingLocation: 'Youth Room',
      projects: ['Youth Retreat', 'Community Service', 'Bible Study Groups'],
      icon: Users,
      color: 'orange',
      joinRequests: []
    },
    { 
      id: 6, 
      name: 'Prayer Ministry', 
      leaders: ['Rev. Ebenezer Adarquah-Yiadom', 'Rev. Lucie Adarquah-Yiadom', 'Gloria Adarquah-Yiadom'],
      assistant: '',
      secretary: '',
      treasurer: '',
      members: 30, 
      membersList: [],
      budget: 5000,
      expenses: 2000,
      description: 'Coordinating prayer meetings and intercession for the church and community',
      meetingDay: 'Multiple days - see prayer schedule',
      meetingTime: 'Various times',
      meetingLocation: 'Prayer Room',
      projects: ['Daily Prayer Meetings', 'Prayer Chain', 'Intercession Groups'],
      icon: Heart,
      color: 'pink',
      joinRequests: []
    }
  ]);